### PR TITLE
WIP: Add tests and improve portability

### PR DESCRIPTION
**Pull request by astrojuanlu**
Frustrated with some problems with FEniCS I tried to get your Firedrake recipes to work. I added tests to all the packages, some missing dependencies and the forked FEniCS subprojects (ufl, fiat and ffc). I am compiling them with conda gcc and gfortran, but it is just a way to ensure I would install as few packages as possible in the build environment and it's safe to use system wide compilers. I replaced netlib LAPACK with OpenBLAS, available through conda official channels.

I am having some problems though:
- I couldn't get PyOP2 to work because of the missing `PETSC_DIR` variable. It's as easy as exporting it though, so it makes me wonder if there is a simpler way to achieve the same result. I don't think DOLFIN has this problem but I might be wrong. post-activate scripts for conda environments would be a nice solution too, but they don't exist.
- I'm seeing an extremely strange error in firedrake when trying to import petsc: apparently the variable is disappearing in the process. I tried to supply a patch but it didn't work.

```
>>> import firedrake.petsc  # This is an unrelated error, wrong FIAT version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/__init__.py", line 30, in <module>
    from firedrake.assemble import *
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/assemble.py", line 10, in <module>
    from firedrake import assemble_expressions
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/assemble_expressions.py", line 17, in <module>
    from firedrake import function
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/function.py", line 14, in <module>
    from firedrake import functionspace
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/functionspace.py", line 5, in <module>
    from FIAT.finite_element import facet_support_dofs
ImportError: cannot import name facet_support_dofs
>>> import firedrake.petsc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/miniconda2/envs/_test/lib/python2.7/site-packages/firedrake/__init__.py", line 3, in <module>
    import firedrake.petsc as petsc
AttributeError: 'module' object has no attribute 'petsc'
```
- I cannot get the forked FFC to work now. First I cannot longer import UFC, and if I remove it from testing all compilation fails.

[I discovered Firedrake two days ago](https://github.com/Juanlu001/pfc/issues/1) so I know very little about the status of the project and its maturity. Travis builds of Firedrake are all green so I fail to see how can it be so difficult to get the recipes to work, but definitely portability issues have their role. Right now Firedrake scripts assume one can `apt-get install` anything and that all the packages are in default root locations.

I don't think I will have the time or the energy to work on this a lot since I have a deadly deadline in some weeks but I hope this work is useful to you and the project. Eventually I would love to see this project generally available through conda - not because I am a conda zealot (which I am, by the way) but to be able to work without virtual machines or Ubuntu-only scripts.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
By the way, this PR addresses #2, #5 and probably #7. I didn't realize there is #1 too, I don't know if your fork of PETSc introduces some significant changes.

**Comment by kynan** [comment]
@Juanlu001 Yes, the PETSc differences are significant. Sorry for not following up on this, neither myself nor @gmarkall are actively working on Firedrake any more and I think the core team do not use conda. @dham @wence-

**Comment by astrojuanlu** [comment]
Oh, my fault then - I assumed you still did. I had outdated information
then :)

**Comment by kynan** [comment]
I haven't had a chance to test your conda build, but here are some guesses:

> I couldn't get PyOP2 to work because of the missing PETSC_DIR variable. It's as easy as exporting it though, so it makes me wonder if there is a simpler way to achieve the same result. I don't think DOLFIN has this problem but I might be wrong. post-activate scripts for conda environments would be a nice solution too, but they don't exist.

`PETSC_DIR` is only required if you install PETSc "by hand". If you use `python setup.py install` PETSc installs a noddy Python module taking care of finding `PETSC_DIR`. Was there a particular reason for changing that?

> I'm seeing an extremely strange error in firedrake when trying to import petsc: apparently the variable is disappearing in the process. I tried to supply a patch but it didn't work.

What would you need this for? Note that this import is _only_ for the purpose of initialising PETSc. It's not intended to be exposed.

> I cannot get the forked FFC to work now. First I cannot longer import UFC, and if I remove it from testing all compilation fails.

Not sure what the issue might be without testing your recipe.

Maybe @gmarkall can weigh in.

**Comment by dham** [comment]
Hi all,

I have to confess that I'm completely ignorant of how conda packaging works, however I can update you on how Firedrake installation works in the general case.

Basically we have now centralised on an install script which we provide at: http://www.firedrakeproject.org/download.html 

This is travis tested to work on OSX and Ubuntu, and we have reports that it works on other Linux too assuming you install the dependencies it tells you to install.

However, at the moment the install script is totally incompatible with anaconda because the install script creates a virtualenv (which is good for avoiding issues with ufl, ffc, FIAT and PETSc versions). However our understanding is that anaconda does not support virtualenvs. 

We are definitely open to suggestions of ways to overcome that hurdle.

**Comment by gmarkall** [comment]
Apologies for the long delay in my replies - at first I was a bit snowed under, then spent about a week ill :-(

@Juanlu001 Many thanks for this PR - this is great! To explain a bit about the files in this repository, I started working on it back before Anaconda build was really ready for general use, so I had been trying out building these recipes on an old laptop of mine. My eventual goal was to get towards continuous builds of all the Firedrake packages on Anaconda cloud, because as you point out it's a really good way to get Firedrake working in many places without requiring Ubuntu, virtualenvs, or VMs. 

Although there are a few issues that you have pointed out with this PR, I'm quite keen to merge it anyway because it's such a huge leap forward on what I already had (and I haven't had a lot of time to add/maintain these recipes anyway). I'll just create an issue to remind myself of the fact that the forked PETSc needs to be used instead of the official releases, and that there might be an issue importing FFC.

@kynan Thanks for adding the info about PETSc!

@dham Thanks for the comments - it is true that conda doesn't support virtualenvs - there's nothing to stop you creating a virtualenv whilst using Anaconda or Miniconda, but conda won't install packages into a virtualenv so you just end up not really using any of the conda packages, and would have to pip install all your requirements. I do strongly believe that having working conda recipes for all the Firedrake packages is a really good way to overcome the hurdle of making it generally and easily installable on many linuxes, which is why I started trying to build these conda recipes originally. In the ideal situation, each time commits are merged to master for any of the Firedrake projects, a new build would automatically be run on Anaconda.org, so that all users can run "conda update firedrake" etc. in order to get the latest version, without the usual hassles of having to pull repos, do a hard reset, rebuild, etc. A while back I also started the PR for COFFEE as a first step towards setting up Anaconda.org builds ( https://github.com/coneoproject/COFFEE/pull/56 ) but hit a hurdle at the time so I never got through to the point of completing it - however, I'll go back and revisit this now as this PR has prompted me to do so.

**Comment by astrojuanlu** [comment]
No need to apologize @gmarkall - glad you're back on track :)

Regarding @kynan suggestions, I recall having problems using `setup.py install` with PETSc in the past so I changed it, but I have not tried it again to be honest. He said that you were not actively working on the project anymore, but anyhow I would be happy to help if you want to push this forward.

**Comment by gmarkall** [comment]
Thankyou - although I am not actively working on the project anymore, I am still very interested in it, I just don't get that much chance to work on conda packaging for it... I do want to push this forward, and hopefully starting with the COFFEE pull request mentioned earlier, which once it is merged I'll set up Anaconda cloud builds for it, then move onto PRing conda recipes for other packages - this repo was where I was keeping recipes I was working on, but for a real chance of the process working successfully, I think the conda and anaconda cloud recipes should be kept in the repos of each project so that they can be maintained together.

**Pull request merged**
